In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('./Occupancy_Estimation.csv')
df.head()

Date      Time  S1_Temp  S2_Temp  S3_Temp  S4_Temp  S1_Light  \
0  2017/12/22  10:49:41    24.94    24.75    24.56    25.38       121   
1  2017/12/22  10:50:12    24.94    24.75    24.56    25.44       121   
2  2017/12/22  10:50:42    25.00    24.75    24.50    25.44       121   
3  2017/12/22  10:51:13    25.00    24.75    24.56    25.44       121   
4  2017/12/22  10:51:44    25.00    24.75    24.56    25.44       121   

   S2_Light  S3_Light  S4_Light  S1_Sound  S2_Sound  S3_Sound  S4_Sound  \
0        34        53        40      0.08      0.19      0.06      0.06   
1        33        53        40      0.93      0.05      0.06      0.06   
2        34        53        40      0.43      0.11      0.08      0.06   
3        34        53        40      0.41      0.10      0.10      0.09   
4        34        54        40      0.18      0.06      0.06      0.06   

   S5_CO2  S5_CO2_Slope  S6_PIR  S7_PIR  Room_Occupancy_Count  
0     390      0.769231       0       0                     1  
1     390      0.646154       0       0                     1  
2     390      0.519231       0       0                     1  
3     390      0.388462       0       0                     1  
4     390      0.253846       0       0                     1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10129 entries, 0 to 10128
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Date                  10129 non-null  object 
 1   Time                  10129 non-null  object 
 2   S1_Temp               10129 non-null  float64
 3   S2_Temp               10129 non-null  float64
 4   S3_Temp               10129 non-null  float64
 5   S4_Temp               10129 non-null  float64
 6   S1_Light              10129 non-null  int64  
 7   S2_Light              10129 non-null  int64  
 8   S3_Light              10129 non-null  int64  
 9   S4_Light              10129 non-null  int64  
 10  S1_Sound              10129 non-null  float64
 11  S2_Sound              10129 non-null  float64
 12  S3_Sound              10129 non-null  float64
 13  S4_Sound              10129 non-null  float64
 14  S5_CO2                10129 non-null  int64  
 15  S5_CO2_Slope       

In [5]:
df.describe()

S1_Temp       S2_Temp       S3_Temp       S4_Temp      S1_Light  \
count  10129.000000  10129.000000  10129.000000  10129.000000  10129.000000   
mean      25.454012     25.546059     25.056621     25.754125     25.445059   
std        0.351351      0.586325      0.427283      0.356434     51.011264   
min       24.940000     24.750000     24.440000     24.940000      0.000000   
25%       25.190000     25.190000     24.690000     25.440000      0.000000   
50%       25.380000     25.380000     24.940000     25.750000      0.000000   
75%       25.630000     25.630000     25.380000     26.000000     12.000000   
max       26.380000     29.000000     26.190000     26.560000    165.000000   

          S2_Light      S3_Light      S4_Light      S1_Sound      S2_Sound  \
count  10129.00000  10129.000000  10129.000000  10129.000000  10129.000000   
mean      26.01629     34.248494     13.220259      0.168178      0.120066   
std       67.30417     58.400744     19.602219      0.316709      0.266503   
min        0.00000      0.000000      0.000000      0.060000      0.040000   
25%        0.00000      0.000000      0.000000      0.070000      0.050000   
50%        0.00000      0.000000      0.000000      0.080000      0.050000   
75%       14.00000     50.000000     22.000000      0.080000      0.060000   
max      258.00000    280.000000     74.000000      3.880000      3.440000   

           S3_Sound      S4_Sound        S5_CO2  S5_CO2_Slope        S6_PIR  \
count  10129.000000  10129.000000  10129.000000  10129.000000  10129.000000   
mean       0.158119      0.103840    460.860401     -0.004830      0.090137   
std        0.413637      0.120683    199.964940      1.164990      0.286392   
min        0.040000      0.050000    345.000000     -6.296154      0.000000   
25%        0.060000      0.060000    355.000000     -0.046154      0.000000   
50%        0.060000      0.080000    360.000000      0.000000      0.000000   
75%        0.070000      0.100000    465.000000      0.000000      0.000000   
max        3.670000      3.400000   1270.000000      8.980769      1.000000   

             S7_PIR  Room_Occupancy_Count  
count  10129.000000          10129.000000  
mean       0.079574              0.398559  
std        0.270645              0.893633  
min        0.000000              0.000000  
25%        0.000000              0.000000  
50%        0.000000              0.000000  
75%        0.000000              0.000000  
max        1.000000              3.000000

In [6]:
df.drop(['Date', 'Time'], axis=1, inplace=True)

In [7]:
df.head()

S1_Temp  S2_Temp  S3_Temp  S4_Temp  S1_Light  S2_Light  S3_Light  S4_Light  \
0    24.94    24.75    24.56    25.38       121        34        53        40   
1    24.94    24.75    24.56    25.44       121        33        53        40   
2    25.00    24.75    24.50    25.44       121        34        53        40   
3    25.00    24.75    24.56    25.44       121        34        53        40   
4    25.00    24.75    24.56    25.44       121        34        54        40   

   S1_Sound  S2_Sound  S3_Sound  S4_Sound  S5_CO2  S5_CO2_Slope  S6_PIR  \
0      0.08      0.19      0.06      0.06     390      0.769231       0   
1      0.93      0.05      0.06      0.06     390      0.646154       0   
2      0.43      0.11      0.08      0.06     390      0.519231       0   
3      0.41      0.10      0.10      0.09     390      0.388462       0   
4      0.18      0.06      0.06      0.06     390      0.253846       0   

   S7_PIR  Room_Occupancy_Count  
0       0                     1  
1       0                     1  
2       0                     1  
3       0                     1  
4       0                     1

In [8]:
df.isnull().sum()

S1_Temp                 0
S2_Temp                 0
S3_Temp                 0
S4_Temp                 0
S1_Light                0
S2_Light                0
S3_Light                0
S4_Light                0
S1_Sound                0
S2_Sound                0
S3_Sound                0
S4_Sound                0
S5_CO2                  0
S5_CO2_Slope            0
S6_PIR                  0
S7_PIR                  0
Room_Occupancy_Count    0
dtype: int64

In [9]:
corr_matrix = df.corr()
corr_matrix['Room_Occupancy_Count'].sort_values(ascending=False)

Room_Occupancy_Count    1.000000
S1_Light                0.849058
S3_Light                0.793081
S2_Light                0.788764
S1_Temp                 0.700868
S7_PIR                  0.695138
S2_Temp                 0.671263
S5_CO2                  0.660144
S3_Temp                 0.652047
S6_PIR                  0.633133
S5_CO2_Slope            0.601105
S1_Sound                0.573748
S2_Sound                0.557853
S3_Sound                0.531685
S4_Temp                 0.526509
S4_Sound                0.460287
S4_Light                0.355715
Name: Room_Occupancy_Count, dtype: float64

In [19]:
df.dtypes

S1_Temp                 float64
S2_Temp                 float64
S3_Temp                 float64
S4_Temp                 float64
S1_Light                  int64
S2_Light                  int64
S3_Light                  int64
S4_Light                  int64
S1_Sound                float64
S2_Sound                float64
S3_Sound                float64
S4_Sound                float64
S5_CO2                    int64
S5_CO2_Slope            float64
S6_PIR                    int64
S7_PIR                    int64
Room_Occupancy_Count      int64
dtype: object

In [16]:
df.shape

(10129, 17)

In [29]:
df['Room_Occupancy_Count'].unique()

array([1, 2, 3, 0], dtype=int64)

In [34]:
from sklearn.model_selection import train_test_split, cross_val_score, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score, confusion_matrix, precision_score, pair_confusion_matrix, recall_score
from scipy.stats import randint

In [21]:
x = df.drop('Room_Occupancy_Count', axis=1)
y = df['Room_Occupancy_Count']

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.transform(X_test)

#Aplicamos PCA para reducir la dimensionalidad
pca = PCA(n_components=0.95)
X_train_pca = pca.fit_transform(X_train_scaler)
X_test_pca = pca.transform(X_test_scaler)

rf_classifier = RandomForestClassifier(random_state=42)

#hiperparametros a explorar
param_dist = {
    'n_estimators': randint(50, 200),
    'max_depth': randint(5, 30),
    'min_samples_split': randint(2, 10),
    'min_samples_leaf': randint(1, 10),
    'max_features': ['auto', 'sqrt']
}

#objeto RandomizedSearchCV
random_search = RandomizedSearchCV(rf_classifier, param_distributions=param_dist, n_iter=20, cv=5, scoring='accuracy', random_state=42)

random_search.fit(X_train_pca, y_train)
best_params = random_search.best_params_

#Se entrena el modelo con los mejores hiperparametros
best_rf_classifier = RandomForestClassifier(**best_params, random_state=42)
best_rf_classifier.fit(X_train_pca, y_train)

#Realiza la validacion cruzada con DecisionTreeClassifier
rf_scores = cross_val_score(best_rf_classifier, X_train_pca, y_train, cv=5, scoring='accuracy') 

c:\Users\aleja\OneDrive\Escritorio\Dev-DS\env\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
35 fits failed out of a total of 100.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
35 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\aleja\OneDrive\Escritorio\Dev-DS\env\Lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\aleja\OneDrive\Escritorio\Dev-DS\env\Lib\site-packages\sklearn\base.py", line 1145, in wrapper
    estimator._validate_params()
  File "c:\Users\aleja\OneDrive\Escritorio\Dev-DS\env\Lib\site-packages\sklearn\base.py", line 638, in _validate_params
  

In [22]:
dt_classifier = DecisionTreeClassifier(random_state=42)

param_dist = {
    'criterion': ['gni', 'entropy'],
    'splitter': ['best', 'random'],
    'max_depth': randint(5, 30),
    'min_samples_split': randint(2, 10),
    'min_samples_leaf': randint(1, 10),
    'max_features': ['auto', 'sqrt']
}

#Se crea el objeto RandomizedSearchCV
random_search = RandomizedSearchCV(dt_classifier, param_distributions=param_dist, n_iter=20, cv=5, scoring='accuracy', random_state=42)

random_search.fit(X_train_pca, y_train)

#Se obtienen los mejores hiperparametros
best_params = random_search.best_params_

#Se entrena el modelo con los mejores hiperparametros
best_dt_classifier = DecisionTreeClassifier(**best_params, random_state=42)
best_dt_classifier.fit(X_train_pca, y_train)

#Realiza la validacion cruzada con DecisionTreeClassifier
dt_scores = cross_val_score(best_dt_classifier, X_train_pca, y_train, cv=5, scoring='accuracy')



c:\Users\aleja\OneDrive\Escritorio\Dev-DS\env\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
65 fits failed out of a total of 100.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
35 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\aleja\OneDrive\Escritorio\Dev-DS\env\Lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\aleja\OneDrive\Escritorio\Dev-DS\env\Lib\site-packages\sklearn\base.py", line 1145, in wrapper
    estimator._validate_params()
  File "c:\Users\aleja\OneDrive\Escritorio\Dev-DS\env\Lib\site-packages\sklearn\base.py", line 638, in _validate_params
  

In [23]:
#Imprimir los resultados de la validacion cruzada
print('Resultados de la validacion cruzada')
print(rf_scores)
print('Promedio de precisión con Random Forest: ', rf_scores.mean())

print("\Resultados de la validacion cruzada Con Decision Tree")
print(dt_scores)
print('Promedio de precisión con Decision Tree: ', dt_scores.mean())

Resultados de la validacion cruzada
[0.98704503 0.98519432 0.98827884 0.98518519 0.98641975]
Promedio de precisión con Random Forest:  0.9864246273828835
\Resultados de la validacion cruzada Con Decision Tree
[0.97223936 0.97285626 0.96483652 0.96790123 0.96481481]
Promedio de precisión con Decision Tree:  0.9685296380073268


In [35]:
#Hacer predicciones con Random Forest
rf_predictions = best_rf_classifier.predict(X_test_pca)

#Hacer predicciones con Decision Tree
dt_predictions = best_dt_classifier.predict(X_test_pca)

#Evaluar el rendimiento del modelo con Random Forest
rf_f1 = f1_score(y_test, rf_predictions, average='weighted')
rf_precision = precision_score(y_test, rf_predictions, average='weighted')
rf_recall = recall_score(y_test, rf_predictions, average='weighted')

print('Rendimiento del modelo con Random Forest')
print('f1 score: ', rf_f1)
print('Precision: ', rf_precision)
print('Recall: ', rf_recall)

#Evaluar el rendimiento del modelo con Decision Tree
dt_f1 = f1_score(y_test, dt_predictions, average='weighted')
dt_precision = precision_score(y_test, dt_predictions, average='weighted')
dt_recall = recall_score(y_test, dt_predictions, average='weighted')

print('\nRendimiento del modelo con Decision Tree')
print('f1 score: ', dt_f1)
print('Precision: ', dt_precision)
print('Recall: ', dt_recall)

#Matriz de confusión con Random Forest
rf_confusion_matrix = confusion_matrix(y_test, rf_predictions)
print(rf_confusion_matrix)

#Matriz de confusión con Decision Tree
dt_confusion_matrix = confusion_matrix(y_test, dt_predictions)
print(dt_confusion_matrix)

Rendimiento del modelo con Random Forest
f1 score:  0.9867469007307088
Precision:  0.9869308967377899
Recall:  0.9866732477788747

Rendimiento del modelo con Decision Tree
f1 score:  0.9675566467561075
Precision:  0.96797097113105
Recall:  0.9674234945705824
[[1615    0    2    2]
 [   0   98    2    3]
 [   0    0  154   10]
 [   3    2    3  132]]
[[1611    1    3    4]
 [   3   92    6    2]
 [   1    0  144   19]
 [   4    2   21  113]]
